name: 'govuln'
description: 'Run tool: govuln'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.24'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - run: govulncheck ./...
      shell: bash
