version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - 'linux'
    goarch:
      - 'amd64'
      - 'arm'
      - 'arm64'
    goarm:
      - '6'
      - '7'

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
    - "ghcr.io/am3o/co2_exporter:{{ .Version }}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.source=https://github.com/am3o/co2_exporter
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "ghcr.io/am3o/co2_exporter:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.source=https://github.com/am3o/co2_exporter
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "ghcr.io/am3o/co2_exporter:{{ .Version }}-armv6"
    goos: linux
    goarch: arm
    goarm: 6
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.source=https://github.com/am3o/co2_exporter
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

  - image_templates:
      - "ghcr.io/am3o/co2_exporter:{{ .Version }}-armv7"
    goos: linux
    goarch: arm
    goarm: 7
    use: buildx
    build_flag_templates:
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.source=https://github.com/am3o/co2_exporter
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/am3o/co2_exporter:{{ .Tag }}
    image_templates:
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-amd64
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-arm64
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-armv7
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-armv6
  - name_template: ghcr.io/am3o/co2_exporter:latest
    image_templates:
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-amd64
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-arm64
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-armv7
      - ghcr.io/am3o/co2_exporter:{{ .Version }}-armv6
