version: '3'

silent: true
tasks:
  init:
    cmds:
      - go work vendor
  build:
    deps:
      - clean
    cmds:
      - go build -ldflags="-s -w" .
  staticcheck:
    deps:
      - init
    cmds:
      - go tool staticcheck ./...
  gosec:
    deps:
      - init
    cmds:
      - go tool gosec ./...
  lint:
    deps:
      - init
    cmds:
      - go tool golangci-lint run ./...
  govuln:
    deps:
      - init
    cmds:
      - go tool govulncheck ./...
  vet:
    cmds:
      - go vet ./...
  test:
    cmds:
      - go test -v -cover -race -shuffle=on ./...
  clean:
    cmds:
      - rm -f co2_exporter
      - rm -rf dist
