name: 'GolangCI'
description: 'Run tool: GolangCI'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.24'
  version:
    description: 'GolangCI-Linter'
    required: false
    default: "v2.0"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
    - uses: golangci/golangci-lint-action@v7
      with:
        version: ${{ inputs.version}}
