name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        step: [ vet, test ]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: ${{ matrix.step }}
        run: make ${{ matrix.step }}

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - golangci
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: build
        run: make build